# .github/workflows/build.yaml
name: Build VirtualElevationRecipes desktop apps

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.4.*

      # ---------- SINGLE-LINE BUILD (no .spec) ----------
      - name: Build app with PyInstaller
        shell: bash                   # Windows runner will auto-convert
        run: |
          # pick the right icon for the current OS
          case "${{ runner.os }}" in
            macOS)   ICON=".assets/VirtualElevationRecipes.icns" ;;
            Windows) ICON=".assets/VirtualElevationRecipes.ico"  ;;
            Linux)   ICON="" ;;   # Linux ignores --icon; desktop files set it later
          esac

          pyinstaller --onefile --windowed --strip --clean \
                      ${ICON:+--icon="$ICON"} \
                      --name "VirtualElevationRecipes" \
                      main.py