# .github/workflows/build.yaml
name: Build VirtualElevationRecipes desktop apps

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==6.4.*

      # ---------- SINGLE-LINE BUILD (no .spec) ----------
      - name: Build app with PyInstaller
        shell: bash                   # Windows runner will auto-convert
        run: |
          # pick the right icon for the current OS
          case "${{ runner.os }}" in
            macOS)   ICON=".assets/VirtualElevationRecipes.icns" ;;
            Windows) ICON=".assets/VirtualElevationRecipes.ico"  ;;
            Linux)   ICON="" ;;   # Linux ignores --icon; desktop files set it later
          esac

          pyinstaller --onefile --windowed --strip --clean \
                      ${ICON:+--icon="$ICON"} \
                      --name "VirtualElevationRecipes" \
                      main.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: VirtualElevationRecipes-${{ runner.os }}
          path: |
            dist/VirtualElevationRecipes*
          retention-days: 5 
          if-no-files-found: error

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist
          
      - name: Prepare release assets
        run: |
          mkdir -p release_files
          # Rename files with platform suffix
          for file in dist/**/VirtualElevationRecipes*; do
            platform=$(echo $file | grep -o 'macOS\|Windows\|Linux')
            filename=$(basename "$file")
            ext="${filename##*.}"
            if [ "$ext" = "$filename" ]; then ext=""; else ext=".$ext"; fi
            cp "$file" "release_files/VirtualElevationRecipes-${platform}${ext}"
          done
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_files/*
          generate_release_notes: true